# Generated by Django 5.0.7 on 2024-08-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.blog'),
        ),
    ]
